### PR TITLE
react-rte and InnerHTML implementation

### PR DESCRIPTION
**Pull request by peroperje**
1. React-rte integration into meeting form 
The component ReachTextEditor contains integration of react-rte. The component is reusable for others forms too. 

2.InnerHTML
Created InnerHTML component. It shows html string of react-rte.

3. small code fix

Note: Update dependencies

### CODE REVIEW

**Comment by peroperje** [comment]
1. Added new component InnerHtmlStripTags
Component extracts text from react-rte html string

**Comment by VGraupera** [comment]
Couple of comments

1. You have a component called "ReachTextEditor" is that a typo? Did you mean RichTextEditor, or WYSIWYG?
2. There are some HTML entities like `&nbsp;` that need escaping. I will attach screenshot below.

1on1_tracker_and_reachtexteditor_js

1on1_tracker_and_reachtexteditor_js____code_2016_1on1tracker_src_components_common__-_vim

**Comment by peroperje** [comment]
About typo.
Sorry. It was my mistake.

About HTML entities like &nbsp; 
Could you tell me, please, how you entered this text?
Did you enter "&nbsp;" into the editor or is it a product of react-rte?

**Comment by VGraupera** [comment]
I was just clicking around and I used the list then clicked monospace which it takes as code block. I must have entered a space not noticing. Here is the HTML that rte returns.

```
<div><p><code>dasdasd</code></p>
<ol>
  <li><code>dasdasd</code></li>
  <li><code>two&nbsp;</code></li>
  <li><code>thee</code></li>
</ol></div>
```

so yes I entered that to answer your questions. Still would be good to suppress.

**Comment by peroperje** [comment]
I am afraid I don't understand.
The component src/components/common/InnerHtmlStripTags.js takes a HTML string and strip tags( it's implementation of [string.js](https://github.com/jprichardson/string.js#--striptagstag1tag2)). It should remove all tags.
I try to cause the same situation, but without success

**Comment by peroperje** [comment]
I think I got it. Let me check, what's going on

**Comment by peroperje** [comment]
It should be fine now. Let me know if you notice something similar

**Pull request merged**
